// Cleo Commands

CMD:skema(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Bulalakars (/skema)", GetRPName(playerid));
	return 1;
}

CMD:xgun(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Weapon Hack (/xgun)", GetRPName(playerid));
	return 1;
}

CMD:slp(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Slap Hack (/slp)", GetRPName(playerid));
	return 1;
}

CMD:fcrash(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Crasher (/fcrash)", GetRPName(playerid));
	return 1;
}

CMD:menu(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Chenh4x Menu (/menu)", GetRPName(playerid));
	return 1;
}

CMD:xcrash(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Crasher (/xcrash)", GetRPName(playerid));
	return 1;
}

CMD:salo(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Aimbot (/salo)", GetRPName(playerid));
	return 1;
}

CMD:ccar(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Invi vehicle (/ccar)", GetRPName(playerid));
	return 1;
}

CMD:kenzo(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Hacks (/kenzo)", GetRPName(playerid));
	return 1;
}

CMD:fspawn(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Fake Spawn (/fspawn)", GetRPName(playerid));
	return 1;
}

CMD:tr(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Troll H4x | Slapper (/tr)", GetRPName(playerid));
	return 1;
}

CMD:takecar(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: H4x | Car Taker (/takecar)", GetRPName(playerid));
	return 1;
}

CMD:follow(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: H4x | Follow Player (/follow)", GetRPName(playerid));
	return 1;
}

CMD:lagtroll(playerid, const params[])
{
	KickPlayer(playerid);
	SMA(COLOR_LIGHTRED, "AdmCmd: %s was kicked by NX:RP BOT, reason: Troll H4x | Lag Troll (/lagtroll)", GetRPName(playerid));
	return 1;
}